import Head from 'next/head'
import { useRouter } from 'next/dist/client/router'
import React from 'react';

export default function Home() {
  const router = useRouter();

  React.useEffect(() => {
    if (localStorage && localStorage.getItem('user')) {
      router.push("/companies");
    } else {
      router.push("/login");
    }
  },[])

  return (
    <div>
      <Head>
        <title>react-redux-thunk</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}
